// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordprocess.proto

/*
Package recordprocessor is a generated protocol buffer package.

It is generated from these files:
	recordprocess.proto

It has these top-level messages:
	Scores
	RecordScore
	GetScoreRequest
	GetScoreResponse
*/
package recordprocessor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import recordcollection "github.com/brotherlogic/recordcollection/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Scores struct {
	Scores []*RecordScore `protobuf:"bytes,1,rep,name=scores" json:"scores,omitempty"`
}

func (m *Scores) Reset()                    { *m = Scores{} }
func (m *Scores) String() string            { return proto.CompactTextString(m) }
func (*Scores) ProtoMessage()               {}
func (*Scores) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Scores) GetScores() []*RecordScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

type RecordScore struct {
	InstanceId int32                                     `protobuf:"varint,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	Rating     int32                                     `protobuf:"varint,2,opt,name=rating" json:"rating,omitempty"`
	Category   recordcollection.ReleaseMetadata_Category `protobuf:"varint,3,opt,name=category,enum=recordcollection.ReleaseMetadata_Category" json:"category,omitempty"`
}

func (m *RecordScore) Reset()                    { *m = RecordScore{} }
func (m *RecordScore) String() string            { return proto.CompactTextString(m) }
func (*RecordScore) ProtoMessage()               {}
func (*RecordScore) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RecordScore) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *RecordScore) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *RecordScore) GetCategory() recordcollection.ReleaseMetadata_Category {
	if m != nil {
		return m.Category
	}
	return recordcollection.ReleaseMetadata_UNKNOWN
}

type GetScoreRequest struct {
	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *GetScoreRequest) Reset()                    { *m = GetScoreRequest{} }
func (m *GetScoreRequest) String() string            { return proto.CompactTextString(m) }
func (*GetScoreRequest) ProtoMessage()               {}
func (*GetScoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetScoreRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type GetScoreResponse struct {
	Scores []*RecordScore `protobuf:"bytes,1,rep,name=scores" json:"scores,omitempty"`
}

func (m *GetScoreResponse) Reset()                    { *m = GetScoreResponse{} }
func (m *GetScoreResponse) String() string            { return proto.CompactTextString(m) }
func (*GetScoreResponse) ProtoMessage()               {}
func (*GetScoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetScoreResponse) GetScores() []*RecordScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

func init() {
	proto.RegisterType((*Scores)(nil), "recordprocessor.Scores")
	proto.RegisterType((*RecordScore)(nil), "recordprocessor.RecordScore")
	proto.RegisterType((*GetScoreRequest)(nil), "recordprocessor.GetScoreRequest")
	proto.RegisterType((*GetScoreResponse)(nil), "recordprocessor.GetScoreResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ScoreService service

type ScoreServiceClient interface {
	GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreResponse, error)
}

type scoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewScoreServiceClient(cc *grpc.ClientConn) ScoreServiceClient {
	return &scoreServiceClient{cc}
}

func (c *scoreServiceClient) GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreResponse, error) {
	out := new(GetScoreResponse)
	err := grpc.Invoke(ctx, "/recordprocessor.ScoreService/GetScore", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ScoreService service

type ScoreServiceServer interface {
	GetScore(context.Context, *GetScoreRequest) (*GetScoreResponse, error)
}

func RegisterScoreServiceServer(s *grpc.Server, srv ScoreServiceServer) {
	s.RegisterService(&_ScoreService_serviceDesc, srv)
}

func _ScoreService_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreServiceServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordprocessor.ScoreService/GetScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreServiceServer).GetScore(ctx, req.(*GetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordprocessor.ScoreService",
	HandlerType: (*ScoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScore",
			Handler:    _ScoreService_GetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordprocess.proto",
}

func init() { proto.RegisterFile("recordprocess.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcd, 0x4a, 0xfc, 0x30,
	0x14, 0xc5, 0xff, 0xfd, 0x0f, 0x96, 0xe1, 0x8e, 0x38, 0x12, 0x41, 0xca, 0x20, 0x58, 0xbb, 0x2a,
	0x2e, 0x52, 0xa8, 0xae, 0xdd, 0x88, 0x5f, 0x0b, 0x17, 0x76, 0x1e, 0x40, 0xd2, 0xf4, 0xd2, 0x09,
	0xd4, 0xde, 0x9a, 0xdc, 0x11, 0x7c, 0x09, 0x9f, 0x59, 0x48, 0x3b, 0x7e, 0x4c, 0x41, 0xc1, 0x5d,
	0xee, 0xc9, 0x39, 0x27, 0x3f, 0x72, 0xe1, 0xc0, 0xa2, 0x26, 0x5b, 0x75, 0x96, 0x34, 0x3a, 0x27,
	0x3b, 0x4b, 0x4c, 0x62, 0xfe, 0x4d, 0x24, 0xbb, 0xb8, 0xaa, 0x0d, 0xaf, 0xd6, 0xa5, 0xd4, 0xf4,
	0x94, 0x95, 0x96, 0x78, 0x85, 0xb6, 0xa1, 0xda, 0xe8, 0xac, 0x37, 0x6a, 0x6a, 0x1a, 0xd4, 0x6c,
	0xa8, 0xcd, 0x7c, 0xc1, 0x48, 0xee, 0x7b, 0x93, 0x0b, 0x08, 0x97, 0x9a, 0x2c, 0x3a, 0x71, 0x0e,
	0xa1, 0xf3, 0xa7, 0x28, 0x88, 0x27, 0xe9, 0x2c, 0x3f, 0x92, 0x5b, 0x4f, 0xca, 0xc2, 0xcf, 0xde,
	0x5e, 0x0c, 0xde, 0xe4, 0x2d, 0x80, 0xd9, 0x17, 0x5d, 0x1c, 0xc3, 0xcc, 0xb4, 0x8e, 0x55, 0xab,
	0xf1, 0xd1, 0x54, 0x51, 0x10, 0x07, 0xe9, 0x4e, 0x01, 0x1b, 0xe9, 0xae, 0x12, 0x87, 0x10, 0x5a,
	0xc5, 0xa6, 0xad, 0xa3, 0xff, 0xfe, 0x6e, 0x98, 0xc4, 0x35, 0x4c, 0xb5, 0x62, 0xac, 0xc9, 0xbe,
	0x46, 0x93, 0x38, 0x48, 0xf7, 0xf2, 0x53, 0x39, 0x62, 0x2e, 0xb0, 0x41, 0xe5, 0xf0, 0x1e, 0x59,
	0x55, 0x8a, 0x95, 0xbc, 0x1c, 0x12, 0xc5, 0x47, 0x36, 0xc9, 0x61, 0x7e, 0x83, 0xdc, 0x43, 0xe2,
	0xf3, 0x1a, 0x1d, 0xff, 0xca, 0x94, 0xdc, 0xc2, 0xfe, 0x67, 0xc6, 0x75, 0xd4, 0x3a, 0xfc, 0xdb,
	0x77, 0xe4, 0x0a, 0x76, 0xbd, 0xb0, 0x44, 0xfb, 0x62, 0x34, 0x8a, 0x07, 0x98, 0x6e, 0x9a, 0x45,
	0x3c, 0x6a, 0xd8, 0x02, 0x5d, 0x9c, 0xfc, 0xe0, 0xe8, 0xb1, 0x92, 0x7f, 0x65, 0xe8, 0x17, 0x77,
	0xf6, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x42, 0xc6, 0xb9, 0x27, 0x02, 0x00, 0x00,
}
